blueprints/auth.py
"""
@Author: 600490
@Email: xianrong.song@resvent.com
@FileName: auth.py
@DataTime: 2023/01/10 19:43
"""
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, session
from exts import mail, db
from flask_mail import Message
import string
import random
from models import EmailCaptchaModel
from .forms import RegisterForm, LoginFrom
from models import UserModel
from werkzeug.security import generate_password_hash, check_password_hash

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginFrom(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                print("用户不存在！")
                return redirect(url_for("auth.login"))
            if check_password_hash(user.password, password):

                session['user_id'] = user.id
                # return "ok"
                return redirect("/")
            else:
                print("密码错误！")
                return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return redirect(url_for("auth.login"))


@bp.route("register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email, username=username, password=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return redirect(url_for("auth.register"))


@bp.route("/loginout")
def loginout():
    session.clear()
    return redirect("/")


@bp.route("/captcha/email")
def get_email_captcha():
    email = request.args.get("email")
    source = string.digits*4
    captcha = random.sample(source, 4)
    print(captcha)
    captcha = "".join(captcha)
    # I/O: Input/Output 耗时
    message = Message(subject='flask注册验证码', recipients=[email], body=f'您的验证码是：{captcha}')
    mail.send(message)
    email_captcha = EmailCaptchaModel(email=email, captcha=captcha)
    db.session.add(email_captcha)
    db.session.commit()
    return jsonify({"code": 200, "message": "", "data": None})


# @bp.route("/mail/test")
# def mail_test():
#     msg = Message(subject='cs', recipients=["1002567463@qq.com"], body='zhegeshi sfds')
#     mail.send(msg)
#     return "ok"

blueprints/qa.py
"""
@Author: 600490
@Email: xianrong.song@resvent.com
@FileName: qa.py
@DataTime: 2023/01/10 19:43
"""
from flask import Blueprint, request, render_template, g, url_for, redirect
from .forms import QuestionForm, AnswerForm
from models import QuestionModel, AnswerModel
from exts import db
from decorators import login_required

bp = Blueprint("qa", __name__, url_prefix="/")


@bp.route("/")
def index():
    questions = QuestionModel.query.order_by(QuestionModel.create_time.desc()).all()
    return render_template("index.html", questions=questions)


@bp.route("/qa/public", methods=['GET', 'POST'])
@login_required
def public_question():
    if request.method == 'GET':
        return render_template('public_question.html')
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect("/")
        else:
            print(form.errors)
            return redirect(url_for("qa.public_question"))


@bp.route("/qa/detail/<qa_id>")
def qa_detail(qa_id):
    question = QuestionModel.query.get(qa_id)
    return render_template("detail.html", question=question)


# @bp.route("/answer/public", methods=['POST'])
@bp.post("/answer/public")
@login_required
def public_answer():
    form = AnswerForm(request.form)
    if form.validate():
        content = form.content.data
        question_id = form.question_id.data
        print("--------")
        print(question_id, content)
        answer = AnswerModel(content=content, question_id=question_id, author_id=g.user.id)
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for("qa.qa_detail", qa_id=question_id))
    else:
        print(form.errors)
        return redirect(url_for("qa.qa_detail", qa_id=request.form.get("question_id")))


@bp.route("/search")
def search():
    q = request.args.get("q")
    questions = QuestionModel.query.filter(QuestionModel.title.contains(q)).all()
    return render_template("index.html", questions=questions)

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css') }}">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">问答</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('qa.public_question') }}">发布问答</a>
                    </li>
                    <li class="nav-item ml-2">
                        <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for('qa.search') }}">
                            <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="q">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                        </form>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if user %}
                        <li class="nav-item">
                            <span class="nav-link" >{{user.username}}</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.loginout') }}">退出登录</a>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">登录</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.register') }}">注册</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block body %}{% endblock %}
<!--        <div class="row" style="margin-top: 20px;">-->
<!--            <div class="col"></div>-->
<!--            <div class="col-10">-->
<!--                <h1 style="text-align: center;">发布问答</h1>-->
<!--                <form action="#" method="post">-->
<!--                    <div class="form-group">-->
<!--                        <input type="text" name="title" class="form-control" placeholder="请输入标题">-->
<!--                    </div>-->
<!--                    <div class="form-group">-->
<!--                        <textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea>-->
<!--                    </div>-->
<!--                    <div class="form-group" style="text-align: right;">-->
<!--                        <button class="btn btn-primary">发布</button>-->
<!--                    </div>-->
<!--                </form>-->
<!--            </div>-->
<!--            <div class="col"></div>-->
<!--        </div>-->

    </div>
</body>

</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}{{ question.title }}{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/detail.css') }}">
{% endblock %}

{% block body %}
<div class="row" style="margin-top: 20px;">
            <div class="col"></div>
            <div class="col-10" style="background-color: #fff;padding: 20px;">
                <h3 class="page-title">{{ question.title }}</h3>
                <p class="question-info">
                    <span>作者：{{ question.author.username }}</span>
                    <span>时间：{{ question.create_time }}</span>
                </p>
                <hr>
                <p class="question-content">{{ question.content }}</p>
                <hr>
                <h4 class="comment-group-title">评论（{{ question.answers|length }}）：</h4>
                <form action="{{ url_for('qa.public_answer') }}" method="post">
<!--                <form action="{{ url_for('qa.public_answer') }}" method="post">-->
                    <div class="form-group">
                        <input type="text" placeholder="请填写评论" name="content" class="form-control">
                        <input type="hidden" name="question_id" value="{{ question.id }}">
                    </div>
                    <div class="form-group" style="text-align: right;">
                        <button class="btn btn-primary">评论</button>
                    </div>
                </form>
                <ul class="comment-group">
                    {% for answer in question.answers %}
                    <li>
                        <div class="user-info">
                            <img class="avatar" src="{{ url_for('static', filename='images/avatar.jpg') }}" alt="">
                            <span class="username">{{ answer.author.username }}</span>
                            <span class="create-time">{{ answer.create_time }}</span>
                        </div>
                        <p class="comment-content">{{ answer.content }}</p>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}登录{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block body %}
<div class="row" style="margin-top: 20px;">
            <div class="col"></div>
            <div class="col-10">
                <ul class="question-ul">
                    {% for question in questions %}
                    <li>
                        <div class="side-question">
                            <img class="side-question-avatar" src="{{ url_for('static', filename='images/avatar.jpg') }}" alt="">
                        </div>
                        <div class="question-main">
                            <div class="question-title"><a href="{{ url_for('qa.qa_detail', qa_id=question.id) }}">{{ question.title }}</a></div>
                            <div class="question-content">{{ question.content }}</div>
                            <div class="question-detail">
                                <span class="question-author">{{ question.author.username }}</span>
                                <span class="question-time">{{ question.create_time }}</span>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}登录{% endblock %}

{% block head %}{% endblock %}

{% block body %}
<div class="row mt-4">
            <div class="col"></div>
            <div class="col">
                <form method="POST">
                    <div class="form-group">
                        <label for="exampleInputEmail1">邮箱</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">密码</label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">立即登录</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

templates/public_question.html
{% extends "base.html" %}

{% block title %}发布问答{% endblock %}

{% block head %}{% endblock %}

{% block body %}
<div class="row" style="margin-top: 20px;">
            <div class="col"></div>
            <div class="col-10">
                <h1 style="text-align: center;">发布问答</h1>
                <form action="#" method="post">
                    <div class="form-group">
                        <input type="text" name="title" class="form-control" placeholder="请输入标题">
                    </div>
                    <div class="form-group">
                        <textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea>
                    </div>
                    <div class="form-group" style="text-align: right;">
                        <button class="btn btn-primary">发布</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %} 注册页面{% endblock %}

{% block head %}
    <script src="{{url_for('static', filename='jquery/jquery.3.6.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/register.js')}}"></script>
{% endblock %}

{% block body %}
<div class="container">
        <div class="row mt-4">
            <div class="col"></div>
            <div class="col">
                <form method="POST">
                    <div class="form-group">
                        <label for="exampleInputEmail1">邮箱</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                        <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用户</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">验证码</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="captcha">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">用户名</label>
                        <input type="text" class="form-control" name="username">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">密码</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">确认密码</label>
                        <input type="password" class="form-control" name="password_confirm">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">立即注册</button>
                </form>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}